[package]
name = "beastiebuddy-app"
version = "1.0.0"
description = "A Final Fantasy XIV companion application for searching creatures and displaying their locations on maps."
authors = ["rail2025"]
edition = "2021"


[lib]
name = "beastiebuddy_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

