// src/bluemage-data.ts
export const bluData = [
  { Number: 1, Name: "Water Cannon", Rank: 1, Sources: [{ Type: "Default", Name: "Default Spell", Location: "N/A" }] },
  { Number: 2, Name: "Flame Thrower", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Gobmachine G-VI", Location: "Brayflox's Longstop (Hard)" }, { Type: "Dungeon", Name: "Magitek Gunship", Location: "The Keeper of the Lake" }, { Type: "Raid", Name: "Omega", Location: "Alphascape V3.0" }] },
  { Number: 3, Name: "Aqua Breath", Rank: 4, Sources: [{ Type: "Trial", Name: "Ultros", Location: "The Dragon's Neck" }, { Type: "Trial", Name: "Leviathan", Location: "The Whorleater (Hard)" }, { Type: "Trial", Name: "Leviathan", Location: "The Whorleater (Extreme)", IsRecommended: false }] },
  { Number: 4, Name: "Flying Frenzy", Rank: 3, Sources: [{ Type: "Open World", Name: "Cornu", Location: "Outer La Noscea", X: null, Y: null }, { Type: "Dungeon", Name: "Zu", Location: "Pharos Sirius" }] },
  { Number: 5, Name: "Drill Cannons", Rank: 2, Sources: [{ Type: "Open World", Name: "Magitek Vanguard H-2", Location: "Northern Thanalan", X: 16, Y: 15 }, { Type: "Dungeon", Name: "Magitek Vanguard", Location: "Castrum Meridianum" }] },
  { Number: 6, Name: "High Voltage", Rank: 4, Sources: [{ Type: "Raid", Name: "ADS", Location: "The Binding Coil of Bahamut - Turn 1" }, { Type: "Raid", Name: "ADS", Location: "The Binding Coil of Bahamut - Turn 2", IsRecommended: false }] },
  { Number: 7, Name: "Loom", Rank: 1, Sources: [{ Type: "Dungeon", Name: "Dantalion", Location: "The Tam-Tara Deepcroft (Hard)" }, { Type: "Open World", Name: "Flame Sergeant Dalvag", Location: "Northern Thanalan" }] },
  { Number: 8, Name: "Final Sting", Rank: 2, Sources: [{ Type: "Open World", Name: "Killer Wespe", Location: "Middle La Noscea", X: 15, Y: 15 }, { Type: "Dungeon", Name: "Temple Bee", Location: "The Sunken Temple of Qarn" }] },
  { Number: 9, Name: "Song of Torment", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Siren", Location: "Pharos Sirius" }, { Type: "Open World", Name: "Aglaope", Location: "Il Mheg" }] },
  { Number: 10, Name: "Glower", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Coincounter", Location: "The Aurum Vale" }, { Type: "Open World", Name: "Eyeclops", Location: "Heritage Found", X: 27, Y: 33.7 }] },
  { Number: 11, Name: "Plaincracker", Rank: 2, Sources: [{ Type: "Open World", Name: "Clay Golem", Location: "North Shroud", X: 19, Y: 29 }, { Type: "Dungeon", Name: "Gogmagolem", Location: "Copperbell Mines (Hard)" }] },
  { Number: 12, Name: "Bristle", Rank: 2, Sources: [{ Type: "Open World", Name: "Wild Boar", Location: "East Shroud", X: 18, Y: 24 }] },
  { Number: 13, Name: "White Wind", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee White Wind Totem", Location: "Learn 10 Blue Magic Spells" }, { Type: "Trial", Name: "Enkidu", Location: "Battle in the Big Keep", IsRecommended: false }] },
  { Number: 14, Name: "Level 5 Petrify", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Manor Sentry", Location: "Haukke Manor" }] },
  { Number: 15, Name: "Sharpened Knife", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Tonberry King", Location: "The Wanderer's Palace" }, { Type: "Open World", Name: "Marberry", Location: "Upper La Noscea" }] },
  { Number: 16, Name: "Ice Spikes", Rank: 1, Sources: [{ Type: "Open World", Name: "Trickster Imp", Location: "Central Shroud", X: 27, Y: 24 }, { Type: "Dungeon", Name: "Manor Jester", Location: "Haukke Manor" }] },
  { Number: 17, Name: "Blood Drain", Rank: 1, Sources: [{ Type: "Open World", Name: "Cave Bat", Location: "Lower La Noscea", X: 27, Y: 16 }, { Type: "Dungeon", Name: "Attic Bat", Location: "Haukke Manor" }] },
  { Number: 18, Name: "Acorn Bomb", Rank: 1, Sources: [{ Type: "Open World", Name: "Treant Sapling", Location: "North Shroud", X: 27, Y: 28 }] },
  { Number: 19, Name: "Bomb Toss", Rank: 2, Sources: [{ Type: "Open World", Name: "Goblin Fisher", Location: "Middle La Noscea", X: 23, Y: 21 }, { Type: "Dungeon", Name: "Illuminati Commander", Location: "Brayflox's Longstop (Hard)" }] },
  { Number: 20, Name: "Off-guard", Rank: 2, Sources: [{ Type: "Totem", Name: "Whalaqee Off-guard Totem", Location: "Learn 5 Blue Magic Spells" }] },
  { Number: 21, Name: "Self-destruct", Rank: 1, Sources: [{ Type: "Open World", Name: "Glide Bomb", Location: "Western Thanalan", X: 27, Y: 16 }, { Type: "Dungeon", Name: "Blasting Cap", Location: "Copperbell Mines" }] },
  { Number: 22, Name: "Transfusion", Rank: 2, Sources: [{ Type: "Totem", Name: "Whalaqee Transfusion Totem", Location: "Learn 20 Blue Magic Spells" }] },
  { Number: 23, Name: "Faze", Rank: 3, Sources: [{ Type: "Open World", Name: "Qiqirn Shellsweeper", Location: "Central Thanalan", X: 16, Y: 19 }] },
  { Number: 24, Name: "Flying Sardine", Rank: 1, Sources: [{ Type: "Open World", Name: "Apkallu", Location: "Eastern La Noscea", X: 27, Y: 35 }] },
  { Number: 25, Name: "Snort", Rank: 4, Sources: [{ Type: "Trial", Name: "Typhon", Location: "The Dragon's Neck" }] },
  { Number: 26, Name: "4-tonze Weight", Rank: 4, Sources: [{ Type: "Trial", Name: "Ultros", Location: "The Dragon's Neck" }] },
  { Number: 27, Name: "The Look", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Anantaboga", Location: "Amdapor Keep" }, { Type: "Raid", Name: "Valefor", Location: "The Labyrinth of the Ancients" }] },
  { Number: 28, Name: "Bad Breath", Rank: 3, Sources: [{ Type: "Open World", Name: "Stroper", Location: "Central Shroud", X: 13, Y: 21 }, { Type: "Dungeon", Name: "Morbol", Location: "The Aurum Vale", IsRecommended: false }] },
  { Number: 29, Name: "Diamondback", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Cuca Fera", Location: "The Stone Vigil (Hard)" }] },
  { Number: 30, Name: "Mighty Guard", Rank: 4, Sources: [{ Type: "Totem", Name: "Whalaqee Mighty Guard Totem", Location: "Learn 10 Blue Magic Spells" }] },
  { Number: 31, Name: "Sticky Tongue", Rank: 4, Sources: [{ Type: "Open World", Name: "Toxic Toad", Location: "Central Thanalan", X: 27, Y: 19 }] },
  { Number: 32, Name: "Toad Oil", Rank: 3, Sources: [{ Type: "Open World", Name: "Giggling Gigantoad", Location: "Western Thanalan", X: 15, Y: 7 }] },
  { Number: 33, Name: "The Ram's Voice", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Chimera", Location: "Cutter's Cry" }, { Type: "Open World", Name: "Gorgimera", Location: "Northern Thanalan", X: 18, Y: 13 }] },
  { Number: 34, Name: "The Dragon's Voice", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Chimera", Location: "Cutter's Cry" }, { Type: "Open World", Name: "Gorgimera", Location: "Northern Thanalan", X: 18, Y: 13 }] },
  { Number: 35, Name: "Missile", Rank: 4, Sources: [{ Type: "Trial", Name: "Enkidu", Location: "Battle in the Big Keep" }, { Type: "Raid", Name: "Guardian", Location: "Sigmascape V3.0" }] },
  { Number: 36, Name: "1000 Needles", Rank: 4, Sources: [{ Type: "Open World", Name: "Sabotender Bailaor", Location: "Southern Thanalan", X: 16, Y: 15 }, { Type: "Dungeon", Name: "Sabotender Desertor", Location: "Cutter's Cry" }] },
  { Number: 37, Name: "Ink Jet", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Kraken", Location: "Sastasha (Hard)" }] },
  { Number: 38, Name: "Fire Angon", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Frumious Koheel Ja", Location: "The Wanderer's Palace (Hard)" }] },
  { Number: 39, Name: "Moon Flute", Rank: 1, Sources: [{ Type: "Totem", Name: "Whalaqee Moon Flute Totem", Location: "Clear 10 Stages in The Masked Carnivale" }] },
  { Number: 40, Name: "Tail Screw", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Karlabos", Location: "Sastasha (Hard)" }, { Type: "Open World", Name: "Crag Claw", Location: "The Peaks", X: 25, Y: 11 }] },
  { Number: 41, Name: "Mind Blast", Rank: 1, Sources: [{ Type: "Dungeon", Name: "Galvanth the Dominator", Location: "The Tam-Tara Deepcroft" }, { Type: "Raid", Name: "Blaster", Location: "Alexander - The Burden of the Son" }] },
  { Number: 42, Name: "Doom", Rank: 4, Sources: [{ Type: "Totem", Name: "Whalaqee Doom Totem", Location: "Clear 20 Stages in The Masked Carnivale" }] },
  { Number: 43, Name: "Peculiar Light", Rank: 2, Sources: [{ Type: "Open World", Name: "Lentic Mudpuppy", Location: "Mor Dhona", X: 13, Y: 10 }, { Type: "Dungeon", Name: "Hellbender", Location: "Brayflox's Longstop" }] },
  { Number: 44, Name: "Feather Rain", Rank: 5, Sources: [{ Type: "Trial", Name: "Garuda", Location: "The Howling Eye (Extreme)" }] },
  { Number: 45, Name: "Eruption", Rank: 5, Sources: [{ Type: "Trial", Name: "Ifrit", Location: "The Bowl of Embers (Extreme)" }] },
  { Number: 46, Name: "Mountain Buster", Rank: 5, Sources: [{ Type: "Trial", Name: "Titan", Location: "The Navel (Extreme)" }] },
  { Number: 47, Name: "Shock Strike", Rank: 5, Sources: [{ Type: "Trial", Name: "Ramuh", Location: "The Striking Tree (Extreme)" }] },
  { Number: 48, Name: "Glass Dance", Rank: 5, Sources: [{ Type: "Trial", Name: "Shiva", Location: "The Akh Afah Amphitheatre (Extreme)" }] },
  { Number: 49, Name: "Veil of the Whorl", Rank: 5, Sources: [{ Type: "Trial", Name: "Leviathan", Location: "The Whorleater (Extreme)" }] },
  { Number: 50, Name: "Alpine Draft", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Opinicus", Location: "The Dusk Vigil" }, { Type: "Open World", Name: "Griffin", Location: "The Sea of Clouds", X: 36, Y: 9 }] },
  { Number: 51, Name: "Protean Wave", Rank: 3, Sources: [{ Type: "Raid", Name: "Living Liquid", Location: "Alexander - The Arm of the Father" }, { Type: "Open World", Name: "Salt and Light", Location: "The Lochs" }] },
  { Number: 52, Name: "Northerlies", Rank: 4, Sources: [{ Type: "Open World", Name: "Lone Yeti", Location: "Coerthas Western Highlands", X: 20, Y: 31 }, { Type: "Dungeon", Name: "Yeti", Location: "Snowcloak" }] },
  { Number: 53, Name: "Electrogenesis", Rank: 2, Sources: [{ Type: "Open World", Name: "Conodont", Location: "The Sea of Clouds", X: 26, Y: 33 }, { Type: "Dungeon", Name: "Hikagiri", Location: "Shisui of the Violet Tides" }] },
  { Number: 54, Name: "Kaltstrahl", Rank: 2, Sources: [{ Type: "Raid", Name: "Faust", Location: "Alexander - The Fist of the Father" }] },
  { Number: 55, Name: "Abyssal Transfixion", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Ash", Location: "Haukke Manor (Hard)" }, { Type: "Dungeon", Name: "The Everliving Bibliotaph", Location: "The Great Gubal Library", IsRecommended: false }] },
  { Number: 56, Name: "Chirp", Rank: 1, Sources: [{ Type: "Open World", Name: "Paissa", Location: "The Sea of Clouds", X: 19, Y: 35 }] },
  { Number: 57, Name: "Eerie Soundwave", Rank: 2, Sources: [{ Type: "Open World", Name: "Empuse", Location: "Azys Lla", X: 29, Y: 12 }, { Type: "Dungeon", Name: "Arioch", Location: "The Lost City of Amdapor" }] },
  { Number: 58, Name: "Pom Cure", Rank: 3, Sources: [{ Type: "Trial", Name: "Furryfoot Kupli Kipp", Location: "Thornmarch (Hard)" }] },
  { Number: 59, Name: "Gobskin", Rank: 4, Sources: [{ Type: "Open World", Name: "Slipkinx Steeljoints", Location: "The Dravanian Hinterlands" }, { Type: "Raid", Name: "Alexandrian Hider", Location: "Alexander - The Breath of the Creator" }] },
  { Number: 60, Name: "Magic Hammer", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Apanda", Location: "The Great Gubal Library (Hard)" }] },
  { Number: 61, Name: "Avail", Rank: 1, Sources: [{ Type: "Dungeon", Name: "Queen Hawk", Location: "Saint Mocianne's Arboretum" }] },
  { Number: 62, Name: "Frog Legs", Rank: 1, Sources: [{ Type: "Open World", Name: "Poroggo", Location: "The Dravanian Hinterlands", X: 12, Y: 34 }] },
  { Number: 63, Name: "Sonic Boom", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Zu", Location: "Pharos Sirius" }, { Type: "Open World", Name: "Anzu", Location: "The Sea of Clouds", X: 25, Y: 6 }] },
  { Number: 64, Name: "Whistle", Rank: 3, Sources: [{ Type: "Open World", Name: "Dhalmel", Location: "The Sea of Clouds", X: 16, Y: 32 }, { Type: "Dungeon", Name: "Dhalmel", Location: "Neverreap" }] },
  { Number: 65, Name: "White Knight's Tour", Rank: 2, Sources: [{ Type: "Dungeon", Name: "White Knight", Location: "The Vault" }] },
  { Number: 66, Name: "Black Knight's Tour", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Black Knight", Location: "The Vault" }] },
  { Number: 67, Name: "Level 5 Death", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Page 64", Location: "The Great Gubal Library" }] },
  { Number: 68, Name: "Launcher", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Armored Weapon", Location: "Baelsar's Wall" }, { Type: "Open World", Name: "Gamma", Location: "Yanxia" }] },
  { Number: 69, Name: "Perpetual Ray", Rank: 4, Sources: [{ Type: "Raid", Name: "The Manipulator", Location: "Alexander - The Burden of the Father" }] },
  { Number: 70, Name: "Cactguard", Rank: 1, Sources: [{ Type: "Dungeon", Name: "Sabotender Guardia", Location: "The Sunken Temple of Qarn (Hard)" }] },
  { Number: 71, Name: "Revenge Blast", Rank: 2, Sources: [{ Type: "Totem", Name: "Whalaqee Revenge Blast Totem", Location: "Learn 50 Blue Magic Spells" }] },
  { Number: 72, Name: "Angel Whisper", Rank: 4, Sources: [{ Type: "Totem", Name: "Whalaqee Angel Whisper Totem", Location: "Clear 30 Stages in The Masked Carnivale" }] },
  { Number: 73, Name: "Exuviation", Rank: 2, Sources: [{ Type: "Open World", Name: "Abalathian Wamoura", Location: "The Sea of Clouds", X: 10, Y: 17 }, { Type: "Dungeon", Name: "Wamoura", Location: "The Lost City of Amdapor" }] },
  { Number: 74, Name: "Reflux", Rank: 3, Sources: [{ Type: "Open World", Name: "Cloud Wyvern", Location: "The Churning Mists", X: 24, Y: 29 }] },
  { Number: 75, Name: "Devour", Rank: 1, Sources: [{ Type: "Dungeon", Name: "the Decaying Gourmand", Location: "The Lost City of Amdapor" }, { Type: "Open World", Name: "Mahisha", Location: "The Lochs" }] },
  { Number: 76, Name: "Condensed Libra", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Mechanoscribe", Location: "The Great Gubal Library (Hard)" }] },
  { Number: 77, Name: "Aetheric Mimicry", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Ghrah Luminary", Location: "Pharos Sirius (Hard)" }] },
  { Number: 78, Name: "Surpanakha", Rank: 5, Sources: [{ Type: "Trial", Name: "Ravana", Location: "Thok ast Thok (Extreme)" }] },
  { Number: 79, Name: "Quasar", Rank: 5, Sources: [{ Type: "Trial", Name: "Sophia", Location: "Containment Bay P1T6" }] },
  { Number: 80, Name: "J Kick", Rank: 5, Sources: [{ Type: "Raid", Name: "Brute Justice", Location: "Alexander - The Burden of the Son" }] },
  { Number: 81, Name: "Triple Trident", Rank: 1, Sources: [{ Type: "Open World", Name: "Ebisu Catfish", Location: "Yanxia", X: 28, Y: 6 }] },
  { Number: 82, Name: "Tingle", Rank: 2, Sources: [{ Type: "Open World", Name: "Ebisu Catfish", Location: "Yanxia", X: 28, Y: 6 }] },
  { Number: 83, Name: "Tatami-gaeshi", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Dojun-maru", Location: "Kugane Castle" }] },
  { Number: 84, Name: "Cold Fog", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Mist Dragon", Location: "The Burn" }] },
  { Number: 85, Name: "Stotram", Rank: 2, Sources: [{ Type: "Trial", Name: "Lakshmi", Location: "Emanation" }] },
  { Number: 86, Name: "Saintly Beam", Rank: 2, Sources: [{ Type: "Raid", Name: "Phantom Train", Location: "Sigmascape V1.0" }] },
  { Number: 87, Name: "Feculent Flood", Rank: 1, Sources: [{ Type: "Dungeon", Name: "Tokkapchi", Location: "Saint Mocianne's Arboretum (Hard)" }, { Type: "Open World", Name: "The Mudman", Location: "Il Mheg" }] },
  { Number: 88, Name: "Angel's Snack", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee Angel's Snack Totem", Location: "Reach Blue Mage level 70" }] },
  { Number: 89, Name: "Chelonian Gate", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Genbu", Location: "Hells' Lid" }] },
  { Number: 90, Name: "The Rose of Destruction", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Ivon Coeurlfist", Location: "The Temple of the Fist" }] },
  { Number: 91, Name: "Basic Instinct", Rank: 2, Sources: [{ Type: "Open World", Name: "Master Coeurl", Location: "Upper La Noscea", X: 8.9, Y: 21.4 }, { Type: "Dungeon", Name: "Coeurl Smriti", Location: "The Temple of the Fist" }] },
  { Number: 92, Name: "Ultravibration", Rank: 1, Sources: [{ Type: "Open World", Name: "Kongamato", Location: "The Peaks", X: 11, Y: 25 }] },
  { Number: 93, Name: "Blaze", Rank: 2, Sources: [{ Type: "Raid", Name: "Alte Roite", Location: "Deltascape V1.0" }] },
  { Number: 94, Name: "Mustard Bomb", Rank: 4, Sources: [{ Type: "Raid", Name: "Omega", Location: "Alphascape V3.0" }] },
  { Number: 95, Name: "Dragon Force", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee Dragon Force Totem", Location: "Learn 100 Blue Magic Spells" }] },
  { Number: 96, Name: "Aetherial Spark", Rank: 1, Sources: [{ Type: "Open World", Name: "Salt Dhruva", Location: "The Lochs", X: 22, Y: 22 }] },
  { Number: 97, Name: "Hydro Pull", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Kelpie", Location: "The Drowned City of Skalla" }] },
  { Number: 98, Name: "Malediction of Water", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Sai Taisui", Location: "The Swallow's Compass" }] },
  { Number: 99, Name: "Choco Meteor", Rank: 1, Sources: [{ Type: "Open World", Name: "Courser Chocobo", Location: "The Dravanian Forelands", X: 37.5, Y: 23.7 }] },
  { Number: 100, Name: "Matra Magic", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee Matra Magic Totem", Location: "Learn 100 Blue Magic Spells" }] },
  { Number: 101, Name: "Peripheral Synthesis", Rank: 4, Sources: [{ Type: "Raid", Name: "Omega", Location: "Alphascape V3.0" }] },
  { Number: 102, Name: "Both Ends", Rank: 5, Sources: [{ Type: "Dungeon", Name: "Qitian Dasheng", Location: "The Swallow's Compass" }] },
  { Number: 103, Name: "Phantom Flurry", Rank: 5, Sources: [{ Type: "Trial", Name: "Suzaku", Location: "Hells' Kier" }] },
  { Number: 104, Name: "Nightbloom", Rank: 5, Sources: [{ Type: "Trial", Name: "Tsukuyomi", Location: "Castrum Fluminis" }] },
  { Number: 105, Name: "Goblin Punch", Rank: 1, Sources: [{ Type: "Open World", Name: "Hobgoblin", Location: "Kholusia", X: 37, Y: 28 }] },
  { Number: 106, Name: "Right Round", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Greater Armadillo", Location: "Malikah's Well" }] },
  { Number: 107, Name: "Schiltron", Rank: 1, Sources: [{ Type: "Open World", Name: "Long-tailed Armadillo", Location: "Amh Araeng", X: 17, Y: 30 }] },
  { Number: 108, Name: "Rehydration", Rank: 1, Sources: [{ Type: "Open World", Name: "Slippery Armadillo", Location: "Amh Araeng", X: 32.5, Y: 9.5 }] },
  { Number: 109, Name: "Breath of Magic", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee Breath of Magic Totem", Location: "Reach Blue Mage level 80" }] },
  { Number: 110, Name: "Wild Rage", Rank: 4, Sources: [{ Type: "Dungeon", Name: "Spectral Berserker", Location: "The Heroes' Gauntlet" }] },
  { Number: 111, Name: "Peat Pelt", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Mudman", Location: "Matoya's Relict" }] },
  { Number: 112, Name: "Deep Clean", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Seeker Of Solitude", Location: "The Grand Cosmos" }] },
  { Number: 113, Name: "Ruby Dynamics", Rank: 4, Sources: [{ Type: "Trial", Name: "The Ruby Weapon", Location: "Cinder Drift" }] },
  { Number: 114, Name: "Divination Rune", Rank: 4, Sources: [{ Type: "Trial", Name: "Titania", Location: "The Dancing Plague" }] },
  { Number: 115, Name: "Dimensional Shift", Rank: 4, Sources: [{ Type: "Raid", Name: "Eden Prime", Location: "Eden's Gate: Resurrection" }] },
  { Number: 116, Name: "Conviction Marcato", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Forgiven Obscenity", Location: "Mt. Gulg" }] },
  { Number: 117, Name: "Force Field", Rank: 3, Sources: [{ Type: "Totem", Name: "Whalaqee Force Field Totem", Location: "Learn 120 Blue Magic Spells" }] },
  { Number: 118, Name: "Winged Reprobation", Rank: 3, Sources: [{ Type: "Trial", Name: "Innocence", Location: "The Crown of the Immaculate" }] },
  { Number: 119, Name: "Laser Eye", Rank: 3, Sources: [{ Type: "Raid", Name: "Eden's Promise", Location: "Eden's Promise: Eternity" }] },
  { Number: 120, Name: "Candy Cane", Rank: 2, Sources: [{ Type: "Dungeon", Name: "Aenc Thon, Lord of the Lingering Gaze", Location: "Dohn Mheg" }] },
  { Number: 121, Name: "Mortal Flame", Rank: 3, Sources: [{ Type: "Dungeon", Name: "Lugus", Location: "The Grand Cosmos" }] },
  { Number: 122, Name: "Sea Shanty", Rank: 5, Sources: [{ Type: "Dungeon", Name: "Nixie", Location: "Matoya's Relict" }] },
  { Number: 123, Name: "Apokalypsis", Rank: 5, Sources: [{ Type: "Dungeon", Name: "Therion", Location: "Amaurot" }] },
  { Number: 124, Name: "Being Mortal", Rank: 5, Sources: [{ Type: "Trial", Name: "Titania", Location: "The Dancing Plague" }] }
];